### ISSUE TITLE
Provision for specifying context path and interpreting no adminPort to be default port (80)

### ISSUE THREAD

**Issue by klnrajareddy** [CafepressDev/newrelic-dropwizard-plugin#3]
Most of the production dropwizard systems are behind a web server, which listen on default port.
This also means that the request forwarding to the dropwizard instance happens by virtue of context path.
However, right now the construction of path can be controlled at host and port level only, leaving no way to specify context path.
Requesting the following functionality
1) Expose a configuration parameter: "adminContext" (optional)
2) Interpret empty admin port to be 80, instead of 8081. 

Modified plugin.template.json would look like:

{
    "_comments": [
        "'name' attribute is optional (if absent, it will default to the same value as 'host')",
        "'adminPort' attribute is optional (if absent, it will default to 8081)"
    ],
    "agents": [
        {
            "name": "appName",
            "host": "localhost",
            "adminContext" : "adminContext",
            "adminPort": 8081
        }
    ]
}

**Comment by dbaggott** [comment]
@klnrajareddy note that this plugin has been replaced by a significantly improved version http://newrelic.com/plugins/iodnbg/48
